[package]
name = "cardinal"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["cargo"] }
thiserror = "1.0.63"
toml = "0.8.15"

[profile.release]
lto = true
strip = "symbols"
